spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:need_for_food}
    username: ${DB_USERNAME:need_for_food}
    password: ${DB_PASSWORD:need_for_food}

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
