spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:need_for_food}
    username: ${DB_USERNAME:need_for_food}
    password: ${DB_PASSWORD:need_for_food}

  jpa:
    show-sql: false

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:need_for_food}:${MONGO_PASSWORD:need_for_food}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/${MONGO_DATABASE:need_for_food}?authSource=admin

logging:
  level:
    org.hibernate.SQL: warn
